<a href="https://colab.research.google.com/github/fatimansilla95-svg/PT1_Mineria_Datos/blob/main/Notebooks/02_preparacion_limpieza_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Carga del dataset**

In [2]:
#1.clonar tu repositorio de Githu
!git clone https://github.com

Cloning into 'github.com'...
fatal: repository 'https://github.com/' not found

In [3]:
import pandas as pd
df = pd.read_json("/content/sample_data/streaming_users_dirty.json")

In [ ]:
df.copy()

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,10000,39,Estándar,805.8,Brasil,Crime,2025-03-04,99
1,10001,37,Estándar,1173.4,Colombia,Crime,2019-04-02,2
2,10002,28,Básico,401.0,Colombia,Crime,2018-04-13,0
3,10003,43,Básico,62.4,Uruguay,Thriller,2021-01-31,0
4,10004,51,Básico,477.8,Perú,Thriller,2020-09-30,1
...,...,...,...,...,...,...,...,...
8155,10923,23,Premium,1161.4,Colombia,Romance,2023-05-15,0
8156,16525,27,Básico,436.2,Uruguay,Documental,2018-09-06,4
8157,11222,13,Estándar,1321.8,México,Documental,2019-02-08,0
8158,15613,38,Estándar,835.7,Brasil,Drama,2022-02-05,0
8159,16912,25,Estándar,1468.7,Argentina,Romance,2022-08-12,3

**Preparación de datos**

Selección de columnas numéricas

In [ ]:
import pandas as pd
df = pd.read_json("/content/sample_data/streaming_users_dirty.json")
num_cols = df.select_dtypes(include="number").columns

**Limpiar y transformar**

In [ ]:
# Eliminar filas duplicadas
df = df.drop_duplicates()

In [ ]:
# Rellenar valores faltantes en columnas numéricas con la mediana
num_cols = df.select_dtypes(include="number").columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

# Rellenar valores faltantes en columnas categóricas con el valor más frecuente
cat_cols = df.select_dtypes(include="object").columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

Eliminamos filas duplicadas
**Usamos la mediana porque es más robusta frente a valores extremos**

## verificar que ya no hay valores nulos

In [ ]:
df.isnull().sum()

user_id                     0
age                         0
subscription_plan           0
monthly_watch_time_mins     0
country                     0
favorite_genre              0
last_login_date             0
customer_support_tickets    0
dtype: int64

## Mostrar tabla limpia

In [ ]:
df.head()

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,10000,39,Estándar,805.8,Brasil,Crime,2025-03-04,99
1,10001,37,Estándar,1173.4,Colombia,Crime,2019-04-02,2
2,10002,28,Básico,401.0,Colombia,Crime,2018-04-13,0
3,10003,43,Básico,62.4,Uruguay,Thriller,2021-01-31,0
4,10004,51,Básico,477.8,Perú,Thriller,2020-09-30,1

In [ ]:
print("Duplicados:", df.duplicated().sum())
print("Valores faltantes:\n", df.isnull().sum())
df.head()

Duplicados: 1
Valores faltantes:
 user_id                     0
age                         0
subscription_plan           0
monthly_watch_time_mins     0
country                     0
favorite_genre              0
last_login_date             0
customer_support_tickets    0
dtype: int64

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,-1.732466,0.336318,Estándar,-0.056257,Brasil,Crime,2025-03-04,8.508725
1,-1.732033,0.198980,Estándar,0.013261,Colombia,Crime,2019-04-02,0.016020
2,-1.731599,-0.419038,Básico,-0.132810,Colombia,Crime,2018-04-13,-0.159087
3,-1.731166,0.610992,Básico,-0.196843,Uruguay,Thriller,2021-01-31,-0.159087
4,-1.730733,1.160342,Básico,-0.118286,Perú,Thriller,2020-09-30,-0.071534

*En la etapa de preparación de datos primero se clono el archivo desde Github para que no se desconecte luego  se eliminaron los registros duplicados y se imputaron valores faltantes. Para las variables numéricas se utilizó la mediana, mientras que para las categóricas se empleó el valor más frecuente. Finalmente, se aplicó un escalamiento estándar a las variables numéricas para garantizar comparabilidad en los análisis posteriores. El dataset quedó limpio y listo para el análisis exploratorio.